//GET Article
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_PENDING = "GET_ARTICLES_PENDING"
export const GET_ARTICLES_REJECTED = "GET_ARTICLES_REJECTED"
export const GET_ARTICLES_FULFILLED = "GET_ARTICLES_FULFILLED"

export const GET_LATEST_ARTICLES = "GET_ARTICLES_ARTICLES"
export const GET_LATEST_ARTICLES_PENDING = "GET_ARTICLES_ARTICLES_PENDING"
export const GET_LATEST_ARTICLES_REJECTED = "GET_ARTICLES_ARTICLES_REJECTED"
export const GET_LATEST_ARTICLES_FULFILLED = "GET_ARTICLES_ARTICLES_FULFILLED"

export const GET_CATEGORY = "GET_CATEGORY"
export const GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING"
export const GET_CATEGORY_FULFILLED = "GET_CATEGORY_FULFILLED"
export const GET_CATEGORY_REJECTED = "GET_CATEGORY_REJECTED"

export const GET_CATEGORYPAGE = "GET_CATEGORYPAGE"
export const GET_CATEGORYPAGE_PENDING = "GET_CATEGORYPAGE_PENDING"
export const GET_CATEGORYPAGE_FULFILLED = "GET_CATEGORYPAGE_FULFILLED"
export const GET_CATEGORYPAGE_REJECTED = "GET_CATEGORYPAGE_REJECTED"

export const GET_ARTICLEPAGE = "GET_ARTICLEPAGE"
export const GET_ARTICLEPAGE_PENDING = "GET_ARTICLEPAGE_PENDING"
export const GET_ARTICLEPAGE_FULFILLED = "GET_ARTICLEPAGE_FULFILLED"
export const GET_ARTICLEPAGE_REJECTED = "GET_ARTICLEPAGE_REJECTED"
